PRODUCTION=0
ifeq ($(PRODUCTION),1)
CODE_READ_PROTECTION=1
CFLAGS=-Wall -O2 -mcpu=arm7tdmi-s -mstructure-size-boundary=8 \
     $(INCLUDES) \
     -DARM=1 \
     -DDEBUG_ENABLED=0 -DASSERT_ENABLED=0 -DBETA=0 -I. -Isoftfloat -Idetector
else
CODE_READ_PROTECTION=0
CFLAGS=-Wall -O2 -mcpu=arm7tdmi-s -mstructure-size-boundary=8 \
       $(INCLUDES) \
       -DARM=1 \
       -DDEBUG_ENABLED=1 -DASSERT_ENABLED=1 -DBETA=1 -I. -Isoftfloat -Idetector
endif
TARGET=arm
