/* detector_config.h
 *
 * Copyright (C)2007 Therodox R&D
 * All rights reserved
 */

#ifndef DETECTOR_CONFIG_H
#define DETECTOR_CONFIG_H

#define DETECTOR_PACKET_LENGTH 512
#define DETECTOR_FFT1_N 64
#define DETECTOR_FRAME_LENGTH DETECTOR_FFT1_N
#define DETECTOR_FRAME_OVERLAP (DETECTOR_FRAME_LENGTH / 4)
#define DETECTOR_DOT_LENGTH 512
#define DETECTOR_DOT_OVERLAP 128
#define DETECTOR_FEATURES (DETECTOR_DOT_LENGTH / 8)

#define DETECTOR_DC_UPDATE_MASK 0xff
#define DETECTOR_DC_SCORE_SAMPLES 16

#define DETECTOR_TD_UPDATE_MASK 0x1f
#define DETECTOR_TD_SCORE_SAMPLES 32
#define DETECTOR_TD_LOW 4
#define DETECTOR_TD_HIGH 16

#define DETECTOR_DROP_FRAMES (8 + (DETECTOR_PACKET_LENGTH / (DETECTOR_FRAME_OVERLAP * DETECTOR_DOT_LENGTH)))
#define DETECTOR_LEARN_FRAMES 64
#define DETECTOR_ADJUST_FRAMES 8

#define DETECTOR_EAS_UP 10
#define DETECTOR_EAS_DOWN 1
#define DETECTOR_EAS_ENTER_LEVEL 4000
#define DETECTOR_EAS_EXIT_LEVEL 2000
#define DETECTOR_EAS_THRESHOLD F(0.05)
#define DETECTOR_EAS_MIN -16384
#define DETECTOR_EAS_MAX 16384

#define DETECTOR_MIN_SIGMA 0x00000010

#define DETECTOR_Z_THRESHOLD 10
#define DETECTOR_ALARM_DECAY F(0.75)
#define DETECTOR_ALARM_THRESHOLD F(2.00)

#endif
